version: '3.8'
services:

  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: